# This file is subject to the terms and conditions defined in
# file 'LICENSE', which is part of this source code package.
#       Copyright (c) 2010 SKR Farms (P) LTD.

"""Change the mapping if the style shortcut for color need to be customized"""

fgcolors = {
    'a'     : 'aquamarine',
    'b'     : 'blue',
    'c'     : 'crimson',
    'd'     : '',
    'e'     : '',
    'f'     : 'fuchsia',
    'g'     : 'green',
    'h'     : '',
    'i'     : 'indigo',
    'j'     : '',
    'k'     : 'khaki',
    'l'     : 'lavender',
    'm'     : 'maroon',
    'n'     : 'navy',
    'o'     : 'orange',
    'p'     : 'pink',
    'q'     : '',
    'r'     : 'red',
    's'     : 'skyBlue',
    't'     : 'teal',
    'u'     : '',
    'v'     : 'violet',
    'w'     : 'white',
    'x'     : '',
    'y'     : 'yellow',
    'z'     : '',
}

bgcolors = {
    'A'     : 'aquamarine',
    'B'     : 'blue',
    'C'     : '',
    'D'     : '',
    'E'     : '',
    'F'     : 'fuchsia',
    'G'     : 'green',
    'H'     : '',
    'I'     : 'indigo',
    'J'     : '',
    'K'     : 'khaki',
    'L'     : 'lavender',
    'M'     : 'maroon',
    'N'     : 'navy',
    'O'     : 'orange',
    'P'     : 'pink',
    'Q'     : '',
    'R'     : 'red',
    'S'     : 'skyBlue',
    'T'     : 'teal',
    'U'     : '',
    'V'     : 'violet',
    'W'     : 'white',
    'X'     : '',
    'Y'     : 'yellow',
    'Z'     : '',
}
